name: Bug report
description: Report a reproducible problem with JobForge
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please include as much detail as possible.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Node, pnpm, Postgres/Supabase versions, and OS
      placeholder: "Node 20.x, pnpm 8.x, Supabase 2.x, macOS 14"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide exact steps or a minimal repro
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and output
      description: Paste relevant logs (redact secrets)
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false
