name: Question / clarification
description: Ask a question about using or extending JobForge
title: "[Question]: "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        For general questions, consider GitHub Discussions (Q&A category).
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Share relevant setup details or links.
    validations:
      required: false
